config/routes.rb
Rails.application.routes.draw do
  get 'jobs', to: 'jobs#index'

  mount ForestLiana::Engine => '/forest'
  get 'about', to: 'main#about'

  get 'contact', to: 'main#contact'

  get 'work', to: 'main#work'

  get 'hmm/surprise', to: 'main#surprise'

  post 'sendemail', to: 'main#create'

  root 'main#index'

end

app/models/job.rb
class Job < ActiveRecord::Base

  scope :ordered_by_start_date, -> { order(date_start: :desc) }
  scope :ordered_by_end_date, -> { order(date_end: :desc) }

  validates_presence_of :name, :company, :date_start, :job_title, :job_type

end

app/models/message.rb
class Message

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :name, :email, :company, :subject, :body, :phone

  validates :name, :email, :subject, :body, :presence => true
  validates :email, :format => { :with => %r{.+@.+\..+} }, :allow_blank => false
  
  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    @jobs = Job.all.ordered_by_end_date
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController

	skip_before_action :verify_authenticity_token

  def about
  end

  def contact
  	@message = Message.new
  end

  def index
  end

  def create

    @message = Message.new(params[:message])

    if @message.valid?

     UserMailer.new_message(@message).deliver
     redirect_to(root_path, :notice => "Thanks for reaching out. I'll get back to you soon!")

      else
    redirect_to(contact_path, :notice => "Sorry you need to include a real email.")

    end
  end

	def surprise
		@due_date = Date.parse('24-04-2017')
		@pretty_date = @due_date.strftime("%A, %b %d, %Y")
		current_date = Date.today
		@days_left = (@due_date - current_date).to_i
		render :layout => false
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/jobs/index.html.haml
.content-area
  .row
    .six.columns
      %h2.work-welcome{:name => "top"} My Projects
    .six.columns
      %button.u-pull-right.download-button
        =link_to "Download Resume", "https://www.dropbox.com/s/om95mpyjx549c1i/JRS%20Resume%20July%202017.pdf?dl=0", class: "downloadlink"
        %i.fa.fa-download.download
  .row.grid
    - @jobs.each do |job|
      .four.columns.listWork.bounce-up.grid-item
        %h4.job-header= job.name
        %p= job.company
        %p
          = job.date_start.nil? ? "" : job.date_start.strftime("%b '%y")
          |
          - if job.date_end.nil?
            = "Present"
          - else
            = job.date_end.strftime("%b '%y")
        %p= job.job_type
        %p= job.network
        %p= job.job_title

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    %title Jenny Rose Starwalt | Production Manager
    / Mobile Specific Metas
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    / Font Icons and Fonts
    %link{:href => "https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css", :rel => "stylesheet"}/
    %link{:href => "https://fonts.googleapis.com/css?family=Pacifico", :rel => "stylesheet", :type => "text/css"}/
    = csrf_meta_tags
    %link{:href => "https://fonts.googleapis.com/css?family=Montserrat", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "https://fonts.googleapis.com/css?family=Nixie+One", :rel => "stylesheet", :type => "text/css"}/
    / Slick
    %link{:href => "//cdn.jsdelivr.net/jquery.slick/1.5.9/slick.css", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "//cdn.jsdelivr.net/jquery.slick/1.5.9/slick-theme.css", :rel => "stylesheet", :type => "text/css"}/
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => false
  %body{:class => "#{controller_name} #{action_name}"}
    / Google Tag Manager
    %noscript
      %iframe{:height => "0", :src => "//www.googletagmanager.com/ns.html?id=GTM-5FPFZG", :style => "display:none;visibility:hidden", :width => "0"}
    :javascript
      (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
      new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
      j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
      '//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
      })(window,document,'script','dataLayer','GTM-5FPFZG');
    / End Google Tag Manager
    .wrapper
      .container
        .row
          %h1.page-header
            %a{:href => "/"} Jenny Rose Starwalt
        .row
          .twelve.columns
            %nav.full_nav
              %ul.nav-list
                %li.nav-item
                  %a.button.nav-button{:href => "/about"} Me
                %li.nav-item
                  %a.button.nav-button{:href => "/jobs"} Resume
                %li.nav-item
                  %a.button.nav-button{:href => "/contact"} Contact
      %hr/
      - if flash[:notice]
        .notice= flash[:notice]
      .container
        = yield
    %footer.bottom
      .footer-content
        .row
          .twelve.cat-image
            %button#catButton.cat-button
              %img.cat{:src => "/cat17.svg"}/
        #copyrightArea.row.copyright-area
          .twelve.columns.copyright
            %p © JennyRoseTV.com 2017
    %script{:src => "//cdn.jsdelivr.net/jquery.slick/1.5.9/slick.min.js", :type => "text/javascript"}

app/views/main/about.html.haml
.content-area
  .welcome
    %h2 Welcome
  .row
    .seven.columns
      %p.resume_text
        I got my start producing live theatre in New York City. I dabbled in short films before transitioning into television as a field producer for “America’s Most Wanted” on FOX.
      %p.resume_text
        These past twelve years working in television, live theater, music videos and film production have brought me to scores of cities throughout the USA and beyond; from haunted castles in England to beach bungalows on remote islands. I thrive on the adventure that comes with every new project, and value the friendships I’ve forged in the field.
      %p.resume_text
        As a production manager and line producer, I believe in doing everything possible to make sure the creative team can completely focus on making a quality product. Producers should never worry about how everyone will be transported to and from set. Camera operators should never wonder whether they will have a hot meal after 6 hours. My teams feel supported and appreciated, and that allows them to create the very best project in their power.
    .five.columns
      .myImage
        = image_tag "/napaIntv.jpg", class:"fun-image"
        = image_tag "/aboutme.jpg", class:"fun-image"
        = image_tag "/beach2.jpg", class: "fun-image"

app/views/main/contact.html.haml
.content-area
  .contact-form
    /
      This form will allow the user to send the owner an email. We'll ask for:
      Name
      Company (limit length)
      Email (validate is an email)
      Text (Description of what they need.)
      We'll want to limit number of emails that
      can be sent.
    = form_for @message, :url => sendemail_path do |f|
      %h4.welcome
        Contact Me
        %span.period .
      %h5.resume_text Thanks for taking the time to stop by. Send me a message if you want to get in touch.
      .row.top_row
        = f.text_field :name,  id: "full_name", class: "six columns", placeholder: "Name"
        = f.text_field :company, id: "company_name", class: "six columns", placeholder: "Company Name"
      .row.top_row
        = f.text_field :email, class: "six columns", placeholder: "Email"
        = f.text_field :phone, class: "six columns", placeholder: "Phone: 932-213-9385"
      .row.top_row
        = f.text_field :subject, class: "twelve columns", placeholder: "Email Subject"
      .row.top_row
        = f.text_area :body, class: "twelve columns user_message", placeholder: "If you have a job or a question for me, let me know here. Or just say hi."
      = f.button id: "sendButton" do
        Send
        %i.fa.fa-paper-plane-o.fa-lg.form_button
    %hr/
    .social-icons
      .row
        .nine.columns
          .social_info
            %h6.helper_text
              Don't like forms? Reach out to me online or just send me an
              %a{:href => "mailto:cleverjenny@gmail.com"} email
              %i (cleverjenny at gmail dot com)
              directly.
        .one.columns.social_links
          %a{:href => "https://www.facebook.com/cleverjenny", :target => "new"}
            %i.fa.fa-facebook-square.fa-2x
        .one.columns.social_links
          %a{:href => "https://www.linkedin.com/in/cleverjenny", :target => "new"}
            %i.fa.fa-linkedin-square.fa-2x
        .one.columns.social_links
          %a{:href => "mailto:cleverjenny@gmail.com", :target => "new", :title => "Click this link to open up your default email."}
            %i.fa.fa-envelope.fa-2x.tooltip

app/views/main/index.html.haml
.content-area
  %h2.welcome Freelance Line Producer for Film and Television
  .carousel
    .photo-div= image_tag("/hgtv_reduced.png", class: "resize")
    .photo-div= image_tag("/vh1.png", class: "resize")
    .photo-div= image_tag("/bio_reduced.png", class: "resize")
    .photo-div= image_tag("/viceland_reduced.png", class: "resize shorty")
    .photo-div= image_tag("/lucky-8_reduced.png", class: "resize shorty")

app/views/main/surprise.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    %title Surprise!
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    / Mobile Specific Metas
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    / Font Icons and Fonts
    %link{:href => "https://fonts.googleapis.com/css?family=Pacifico", :rel => "stylesheet", :type => "text/css"}/
    = csrf_meta_tags
    %link{:href => "https://fonts.googleapis.com/css?family=Montserrat", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "https://fonts.googleapis.com/css?family=Nixie+One", :rel => "stylesheet", :type => "text/css"}/
  %body{:class => "#{controller_name} #{action_name}"}
    .wrapper
      %h1 We are pregnant!
      %p Due Date: #{@pretty_date}
      %p
        There are only
        = @days_left
        days left though!
      %h2
        We found out that we are having a
        %span#secretAnnouncement.notCorrect
          hmm
        %span><
          !

  :javascript
      function ran_col() {
        var color = '#';
        var letters = ['#ecf0f1', 'BFE9EA', '80CFA9', 'FEFCFD', 'FFEEDB'];
        color += letters[Math.floor(Math.random() * letters.length)];
        document.querySelector('body').style.background = color;
      }
      ran_col();
      function make_text() {
        // make array
        var sex = ["boy", "girl", "cat"];
        //Grab the element that we want to change.
        var x = document.getElementById('secretAnnouncement');
        // Randomize some stuff.
        var value = sex[Math.floor(Math.random() * sex.length)];

        window.setTimeout( "make_text()", 1000);
        function change_text() {
          x.innerHTML = value;
        }

        if (x.textContent == "boy") {
          x.classList.remove("notCorrect");
          x.classList.add("aBoy");
          return;
        }
        change_text();
      };
      make_text();

app/views/main/work.html.haml
.content-area
  .row
    .six.columns
      %h2.work-welcome{:name => "top"} My Projects
    .six.columns
      %button.u-pull-right.download-button
        =link_to "Download Resume", "https://www.dropbox.com/s/w6efo086i13sk3e/Jenny%20Rose%20Resume%20Aug%202016.pdf?dl=0", class: "downloadlink"
        %i.fa.fa-download.download
  .row
    .four.columns.listWork.bounce-up
      %h4.job-header Development
      %p Lucky 8 TV
      %p July '16' - present
      %p Various Development Projects
      %p Multiple Networks
      %p Production Manager
    .four.columns.listWork.bounce-up
      %h4.job-header Gaycation
      %p VICE Media
      %p March '16 - Jul '16'
      %p Documentary / Travel Series
      %p VICELAND
      %p Production Manager
    .four.columns.listWork.bounce-up
      %h4.job-header The Haunting Of...
      %p Jarrett Creative
      %p Feb '12 - Jan '16
      %p Celebrity / Travel Series
      %p BIO / LMN
      %p Production Manager
    .four.columns.listWork.bounce-up
      %h4.job-header Vacation House For Free
      %p Departure Films
      %p Oct '14 - Jul '15
      %p Home Renovation / Travel Series
      %p HGTV
      %p Production Manager
    .four.columns.listWork.bounce-up
      %h4.job-header This is Hot 97
      %p Eastern / NFGTV
      %p Oct '13 - Feb '14
      %p Mocumentary Comedy Series
      %p VH1
      %p Production Manager
    .four.columns.listWork.bounce-up
      %h4.job-header Chrissy and Mr. Jones
      %p Eastern / NFGTV
      %p Jun - Oct '13
      %p Follow-Doc Reality Series
      %p VH1
      %p Production Manager
    .four.columns.listWork.bounce-up
      %h4.job-header Boston's Finest
      %p Jarrett Creative
      %p Dec '12 - Feb '13
      %p Follow-Doc Cop Series
      %p TNT
      %p Production Manager
    .four.columns.listWork.bounce-up
      %h4.job-header Mansome
      %p Warrior Poets
      %p Jun - Nov &#x2018;12
      %p Comedy Web Series
      %p Yahoo! Screen
      %p Associate Producer
    .four.columns.listWork.bounce-up
      %h4.job-header School Spirits
      %p Jarrett Creative
      %p Mar - May &#x2018;12
      %p Interview / Recreation Series
      %p SYFY
      %p Production Manager
    .four.columns.listWork.bounce-up
      %h4.job-header Celebrity House Hunting
      %p Departure Films
      %p Sep &#x2019;11 - Mar &#x2018;12
      %p House Hunting / Travel Series
      %p BIO
      %p Production Manager
    .four.columns.listWork.bounce-up
      %a{:href => "http://www.youtube.com/watch?v=dcZu9EQBpk0", :target => "new"}
        %h4.job-header Money From Strangers
      %p Lion Television
      %p Jul - Sept &#x2018;11
      %p Hidden Camera Game Show
      %p MTV
      %p Field Production Manager  2nd AD
    .four.columns.listWork.bounce-up
      %h4.job-header Work of Art
      %p Magical Elves
      %p 2009 - 2011
      %p Reality Competition Series
      %p BRAVO
      %p Production Manager
    .four.columns.listWork.bounce-up
      %h4.job-header Mob Wives
      %p Left/Right
      %p Mar - Jul &#x2018;11
      %p Follow-Doc Reality Series
      %p VH1
      %p Production Manager
    .four.columns.listWork.bounce-up
      %h4.job-header Saved
      %p Picture Shack
      %p Jan - Apr &#x2018;11
      %p Documentary / Travel Series
      %p Animal Planet
      %p Production Coordinator
    .four.columns.listWork.bounce-up
      %h4.job-header The Haunted
      %p Picture Shack
      %p Oct '10 - Jan &#x2018;11
      %p Documentary / Travel Series
      %p Animal Planet
      %p Production Coordinator
    .four.columns.listWork.bounce-up
      %h4.job-header Bridge Tunnel
      %p MTV Networks
      %p May - Oct &#x2018;10
      %p Follow-Doc Reality Series
      %p MTV
      %p Production Coordinator
    .four.columns.listWork.bounce-up
      %h4.job-header Happy New Year
      %p Happy New Year LLC
      %p 2009
      %p Feature Film
      %p Festival Limited Theatrical Release
      %p Unit Production Manager
    .four.columns.listWork.bounce-up
      %h4.job-header America's Most Wanted
      %p FOX Network
      %p 2005-2006
      %p Reality Crime series
      %p FOX
      %p Field Producer
    .four.columns.listWork.bounce-up
      %h4.job-header World of Wealth
      %p Re:Source Media
      %p 2004-2005
      %p Interview Series
      %p Wealth TV
      %p Field Producer
  .up
    %a{:href => "#top"}
      %i.fa.fa-arrow-up.fa-lg